"""
Files on disk, per document:

  storage/<document_id>/originals/<n>.<ext>     uploaded files, untouched
  storage/<document_id>/pages/page-<n>.jpg      normalized page images
  storage/<document_id>/versions/v<n>.json      AI draft, saved reviews, approved version
"""

import json
import re
from pathlib import Path
from typing import Any

from .config import settings


def document_dir(document_id: str) -> Path:
    # Ids are generated by us (uuid hex); the check keeps any path trick out.
    if not re.fullmatch(r"[0-9a-f]{32}", document_id):
        raise ValueError("invalid document id")
    return settings.storage_dir / document_id


def originals_dir(document_id: str) -> Path:
    return document_dir(document_id) / "originals"


def pages_dir(document_id: str) -> Path:
    return document_dir(document_id) / "pages"


def page_path(document_id: str, number: int) -> Path:
    return pages_dir(document_id) / f"page-{number}.jpg"


def write_version(document_id: str, version: int, payload: dict[str, Any]) -> str:
    folder = document_dir(document_id) / "versions"
    folder.mkdir(parents=True, exist_ok=True)
    file_name = f"v{version}.json"
    (folder / file_name).write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")
    return file_name


def read_version(document_id: str, file_name: str) -> dict[str, Any]:
    return json.loads((document_dir(document_id) / "versions" / file_name).read_text(encoding="utf-8"))
